### ISSUE TITLE
Audio recorded affected on some devices when 'configuration.providesAudioData' = true is used'.

### ISSUE THREAD

**Issue by hizzlehoff** [gorastudio-ceo/SCNRecorder#38]
When using:

let configuration = ARWorldTrackingConfiguration()
configuration.providesAudioData = true
sceneView.session.run(configuration)

On some devices (like iPad pro and iPhone 12) the volume for recording using AVFoundation's AVAudioRecorder is dramatically reduced. If anyone knows a solution for this I'd be very grateful.

**Comment by v-grigoriev** [comment]
There doesn't seem to be an answer yet and the issue is not related to SCNRecorder. Closing.
