### ISSUE TITLE
Requires NSCameraUsageDescription always

### ISSUE THREAD

**Issue by giomurru** [gorastudio-ceo/SCNRecorder#43]
When I submit to appstore connect I get an error saying that it is required to have NSCameraUsageDescription key, even though I am not using the camera because I am recording only a ScnView. 
Is there a way to disable the part relative to the camera API in the SDK so that Apple does not require NSCameraUsageDescription key?

**Comment by v-grigoriev** [comment]
Hi @giomurru, a good catch.
The SDK doesn't use the camera by any means.
But I think it happens because the SDK imports ARKit in several places.
So, you can safely give any NSCameraUsageDescription.
And I can look at moving ARKit-related functionality to a submodule.

**Comment by v-grigoriev** [comment]
@giomurru  What dependency manager are you using? Cocoapods?

**Comment by giomurru** [comment]
Thank you. That would be great. Yes I am using Cocapods.

**Comment by giomurru** [comment]
@v-grigoriev I found the file that is causing the issue. :-) 
It's `AVCaptureSession+BaseRecorder.swift`
Since I am not using it I just removed it from the target and now when I submit the app to appstoreconnect I don't have any issue of missing NSCameraUsageDescription.
