### ISSUE TITLE
Swift 5.7 support

### ISSUE THREAD

**Issue by cpheinrich** [gorastudio-ceo/SCNRecorder#46]
Unfortunately building my project that uses SCNRecorder with the latest XCode 14 beta results in a few build errors in this module. Hopefully it is an easy fix. Thank you!
![image](https://user-images.githubusercontent.com/12475454/172524160-236a331b-96a7-4b1e-85fa-da2f57f97dbc.png)

**Comment by v-grigoriev** [comment]
Thank you @cpheinrich!
