### ISSUE TITLE
It's time to type the new tag.

### ISSUE THREAD

**Issue by xiaoMing0109** [gorastudio-ceo/SCNRecorder#49]
Hello, it's time to type the new tag about
**3f316b05d6aa3c697689fb9a7c7e6e7b0b11d48e**.

**Comment by rogerioth** [comment]
Yes, can you guys create the new tag with the current version, please? @v-grigoriev, @gorastudio-ceo, @AlexKurenkov I've tried tons of alternative methods but in the end, only a 2.7.1 tag will solve it for me :(

**Comment by v-grigoriev** [comment]
I did 2.8.0, some-why I didn't release it as a patch ¯\_(ツ)_/¯

**Comment by rogerioth** [comment]
Thank you so much!
