### ISSUE TITLE
ARView+SelfSceneRecordable Crash

### ISSUE THREAD

**Issue by frank-1992** [gorastudio-ceo/SCNRecorder#56]
When I set the minimum deployments 'iOS 10.0' and run the example , 

`_cancelable = scene.subscribe(
        to: SceneEvents.Update.self
      ) { [weak sceneRecorder] (_) in
        sceneRecorder?.render()
      }`
SceneEvents.Update will crash, can you help to me?

**Comment by v-grigoriev** [comment]
RealityKit is iOS 13+, there are known issues with lower version usage, maybe https://stackoverflow.com/questions/71000365/realitykit-app-and-lower-ios-deployment-target will help you.

**Comment by v-grigoriev** [comment]
iOS 16 is available already I will be dropping iOS 12 support anytime soon.

**Comment by frank-1992** [comment]
> RealityKit is iOS 13+, there are known issues with lower version usage, maybe https://stackoverflow.com/questions/71000365/realitykit-app-and-lower-ios-deployment-target will help you.

thank you

**Comment by frank-1992** [comment]
> RealityKit is iOS 13+, there are known issues with lower version usage, maybe https://stackoverflow.com/questions/71000365/realitykit-app-and-lower-ios-deployment-target will help you.

I have participated in the discussion below this link. Now that xcode14 has been fixed, can the code here be used without combine?

**Comment by v-grigoriev** [comment]
> I have participated in the discussion below this link. Now that xcode14 has been fixed, can the code here be used without combine?

SceneRecorder needs to be notified when a new frame rendered.
If you can find another approach to get such information form RealityKit you are welcome to contribute :)

you can trigger sceneRecorder?.render() manually, for example by timer or CADisplayLink, but it will be inaccurate.

**Comment by frank-1992** [comment]
> > I have participated in the discussion below this link. Now that xcode14 has been fixed, can the code here be used without combine?
> 
> SceneRecorder needs to be notified when a new frame rendered. If you can find another approach to get such information form RealityKit you are welcome to contribute :)
> 
> you can trigger sceneRecorder?.render() manually, for example by timer or CADisplayLink, but it will be inaccurate.

Thanks for your answer, I will try it

**Comment by frank-1992** [comment]
> > I have participated in the discussion below this link. Now that xcode14 has been fixed, can the code here be used without combine?
> 
> SceneRecorder needs to be notified when a new frame rendered. If you can find another approach to get such information form RealityKit you are welcome to contribute :)
> 
> you can trigger sceneRecorder?.render() manually, for example by timer or CADisplayLink, but it will be inaccurate.

I have finished it.  Can you help to check it, is it ok?
`@available(iOS 13.0, *)
extension SceneRecorder: ARSessionDelegate {
  public func session(_ session: ARSession, didUpdate frame: ARFrame) {
    render()
  }
}`

**Comment by frank-1992** [comment]
`import Foundation
import RealityKit
import SCNRecorder
import Combine
import ARKit

private var cancellableKey: UInt8 = 0

@available(iOS 13.0, *)
extension ARView: SelfSceneRecordable {

  var _cancelable: Cancellable? {
    get {
      objc_getAssociatedObject(
        self,
        &cancellableKey
      ) as? Cancellable
    }
    set {
      objc_setAssociatedObject(
        self,
        &cancellableKey,
        newValue,
        .OBJC_ASSOCIATION_RETAIN
      )
    }
  }

  public func injectRecorder() {
    do {
      sceneRecorder = try SceneRecorder(self)
      #if !targetEnvironment(simulator)
      session.delegate = sceneRecorder
      #endif
    }
    catch { assertionFailure("\(error)") }
  }
}


@available(iOS 13.0, *)
extension SceneRecorder: ARSessionDelegate {
  public func session(_ session: ARSession, didUpdate frame: ARFrame) {
    render()
  }
}
`
I have tested it

**Comment by v-grigoriev** [comment]
hm, interesting, it should be a bit inaccurate but fine.

**Comment by frank-1992** [comment]
> inaccurate

emmm,   but my project must be set to iOS10.0(minimum deployments)

**Comment by v-grigoriev** [comment]
please don't confirm third party classes to third party protocols. it might lead to unexpected results.
I don't remember if I used session delegate somewhere inside the library, if not it should be fine.

It might be a bit inaccurate because the `session(_ session: ARSession, didUpdate frame: ARFrame)` function is called a moment before the content is rendered. But it might be ok.

**Comment by v-grigoriev** [comment]
Another thing here is that the content might be changed from somewhere else, without changing ARFrame, so this callback won't fire. but It should still work for reality kit.

**Comment by frank-1992** [comment]
> 

public func renderer(_ renderer: SCNSceneRenderer, updateAtTime time: TimeInterval) ok thanks for your suggestion, do you think this protocol will be better?

**Comment by v-grigoriev** [comment]
> public func renderer(_ renderer: SCNSceneRenderer, updateAtTime time: TimeInterval) ok thanks for your suggestion, do you think this protocol will be better?

it will, but RealityKit doesn't use SceneKit, so it just won't work.
You can just create you own delegate conforming to ARSessionDelegate and call render from there.
