### ISSUE TITLE
When I install pod 'SCNRecorder', '~> 2.8.0', the code installed is different from master branch

### ISSUE THREAD

**Issue by frank-1992** [gorastudio-ceo/SCNRecorder#57]
Can you help to check it ? Thank you

**Comment by frank-1992** [comment]
I think it should be given a new tag 2.8.1 or 2.9.0

**Comment by v-grigoriev** [comment]
yes, because I forgot to release yesterday. I'm releasing it now.

**Comment by frank-1992** [comment]
> yes, because I forgot to release yesterday. I'm releasing it now.

OK, thank you
